version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      
    healthcheck:
      test: bash -c "echo 0"
      interval: 30s
      timeout: 5s
      retries: 3
networks:
  custom:
    name: music-db